lab_1/urls.py
from django.urls import path
from . import views

app_name = 'lab_1'

urlpatterns = [
    path('', views.index, name='indexlab1'),
    path('friendlist/', views.friend_list, name='friend_list')
]

lab_2/urls.py
from django.urls import path
from . import views

app_name = 'lab_2'

urlpatterns = [
    path('', views.index, name='indexlab2'),
    path('xml/', views.xml, name='xml'),
    path('json/', views.json, name='json'),
]

lab_3/urls.py
from django.urls import path
from . import views

app_name = 'lab_3'

urlpatterns = [
    path('', views.index, name='indexlab3'),
    path('add_friend/', views.form, name='formlab3')
]

lab_4/urls.py
from django.urls import path
from . import views

app_name = 'lab_4'

urlpatterns = [
    path('', views.index, name='indexlab4'),
    path('add_note/', views.createform, name='createform4'),
    path('card_note/<int:note_id>/', views.note_card, name='cardnote'),
    path('edit_note/<int:note_id>/', views.editform, name='editform4'),
    path('delete_note/<int:note_id>/', views.deleteform, name='deleteform4')
]

praktikum/urls.py
from django.urls import path, re_path, include
from django.contrib import admin
from lab_1.views import index as index_lab1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lab-1/', include('lab_1.urls')),
    path('lab-2/', include('lab_2.urls')),
    path('lab-3/', include('lab_3.urls')),
    path('lab-4/', include('lab_4.urls')),
    re_path(r'^$', index_lab1, name='index')
]

lab_1/models.py
from django.db import models

# TODO Create Friend model that contains name, npm, and DOB (date of birth) here

class Friend(models.Model):
    name = models.CharField(max_length=30)
    npm = models.CharField(max_length=10)
    DOB = models.DateField()

lab_2/models.py
from django.db import models

# Create your models here.
class Note(models.Model):
    untuk = models.CharField(max_length=30)
    dari = models.CharField(max_length=30)
    title = models.CharField(max_length=50)
    message = models.TextField()

lab_3/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

lab_3/forms.py
from django.forms import ModelForm
from lab_1.models import Friend

class FriendForm(ModelForm):
    class Meta:
        model = Friend
        fields = '__all__'

    

lab_4/forms.py
from django.forms import ModelForm
from lab_2.models import Note

class NoteForm(ModelForm):
    class Meta:
        model = Note
        fields = '__all__'

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
from .models import Friend

mhs_name = "Mikael Alvian Rizky"
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2003, 8, 10)  
npm = 2006596592  

def index(request):
    response = {'name': mhs_name,
                'age': calculate_age(birth_date.year),
                'npm': npm}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

def friend_list(request):
    friends = Friend.objects.all()
    response = {'friends': friends}
    return render(request, 'friend_list_lab1.html', response)

lab_2/views.py
from django.shortcuts import render
from django.http.response import HttpResponse
from django.core import serializers
from .models import Note
# Create your views here.

def index(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'lab2.html', response)

def xml(request):
    data = serializers.serialize('xml', Note.objects.all())
    respon = HttpResponse(data, content_type="application/xml")
    return respon

def json(request):
    data = serializers.serialize('json', Note.objects.all())
    return HttpResponse(data, content_type="application/json")

lab_3/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import FriendForm
from django.contrib import messages
from lab_1.models import Friend
from django.contrib.auth.decorators import login_required

@login_required(login_url='/admin/login')
def index(request):
    friends = Friend.objects.all()
    return render(request, 'indexlab3.html', {'friends': friends})

@login_required(login_url='/admin/login')
def form(request):
    form = FriendForm()

    if(request.method == "POST"):
        form =  FriendForm(request.POST)
        if(form.is_valid()):
            form.save()
            messages.success(request, "Friend created successfully")
            return HttpResponseRedirect("/lab-3")

    return render(request, 'formlab3.html', {'form':form})

lab_4/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.contrib import messages
from lab_2.models import Note
from .forms import NoteForm

# Create your views here.
def index(request):
    notes = Note.objects.all()
    response = {'notes': notes}
    return render(request, 'indexlab4.html', response)

def createform(request):
    form = NoteForm()

    if(request.method == "POST"):
        form =  NoteForm(request.POST)
        if(form.is_valid()):
            form.save()
            messages.success(request, "Note created successfully")
            return HttpResponseRedirect("/lab-4")
    return render(request, 'formlab4.html', {'form':form})

#belum
def editform(request, note_id):
    note = Note.objects.get(id=note_id)
    return render(request, 'editform4.html', {'note':note})

def deleteform(request, note_id):
    Note.objects.get(id=note_id).delete()
    messages.error(request, "Note deleted successfully")
    return HttpResponseRedirect("/lab-4")

def note_card(request, note_id):
    note = Note.objects.get(id=note_id)
    return render(request, 'notecard.html', {'note':note})

lab_1/templates/friend_list_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table class="table table-hover table-bordered"> 
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      {% for friend in friends %}
      <tr>
        <td>{{ friend.name }}</td>
        <td>{{ friend.npm }}</td>
        <td>{{ friend.DOB }}</td>
      </tr>
      {% endfor %}

    </table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>{{ name }}</title>
  </head>
  <body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
  </body>
</html>

lab_2/templates/lab2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table class="table table-hover table-bordered">
      <tr>
        <th scope="col">Untuk</th>
        <th scope="col">Dari</th>
        <th scope="col">Title</th>
        <th scope="col">Message</th>
      </tr>
      <!-- TODO loop from Friend model -->
      {% for note in notes %}
      <tr>
        <td>{{ note.untuk }}</td>
        <td>{{ note.dari }}</td>
        <td>{{ note.title }}</td>
        <td>{{ note.message }}</td>
      </tr>
      {% endfor %}

    </table>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>
</html>

lab_3/templates/formlab3.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FriendForm</title>
</head>
<body>
    <h3>FriendForm</h3>
    <hr>
    
    <form action="" method="POST">
        {%csrf_token%}
        {{form|crispy}}
        <a href="{% url 'lab_3:indexlab3' %}" class="btn btn-primary">Back</a>
        <input type="submit" class="btn btn-secondary">
    </form>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</body>
</html>

lab_3/templates/indexlab3.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <meta charset="UTF-8" />
    <title>Friend List</title>
  </head>
  <body>
    <table class="table table-hover table-bordered"> 
      <tr>
        <th>Name</th>
        <th>NPM</th>
        <th>DOB</th>
      </tr>
      <!-- TODO loop from Friend model -->
      {% for friend in friends %}
      <tr>
        <td>{{ friend.name }}</td>
        <td>{{ friend.npm }}</td>
        <td>{{ friend.DOB }}</td>
      </tr>
      {% endfor %}
    </table>
    <a href="{% url 'lab_3:formlab3' %}" class="btn btn-primary">Add Friend</a>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>
</html>

lab_4/templates/editform4.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
        <meta charset="UTF-8">
        <title>Edit NoteForm</title>

    </head>

    <body>
        <h3>NoteForm</h3>
        <h1>BELUM</h1>
        <hr>
        
        <form action="" method="POST">
            {%csrf_token%}
            <div class="mb-3">
                <label for="formGroupExampleInput" class="form-label">Example label</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder">
              </div>
              <div class="mb-3">
                <label for="formGroupExampleInput2" class="form-label">Another label</label>
                <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder">
            </div>
            <a href="{% url 'indexlab4' %}" class="button button1">Back</a>
            <input type="submit" class="button button2">
        </form>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
    </body>
</html>

lab_4/templates/formlab4.html
<!DOCTYPE html>
{% load crispy_forms_tags %}
<html lang="en">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
        <meta charset="UTF-8">
        <title>NoteForm</title>
        <!-- https://www.w3schools.com/css/tryit.asp?filename=trycss_buttons_hover -->
        <style>
            .button {
            background-color: #4c5caf; /* Green */
            border: none;
            color: white;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
            }
            .button1 {padding: 10px 24px;}

            .button1 {
            background-color: white; 
            color: black; 
            border: 2px solid #4c5caf;
            }  
            .button1:hover {
            background-color: #4c5caf;
            color: white;
            }

            .button2 {padding: 10px 24px;}

            .button2 {
            background-color: white; 
            color: black; 
            border: 2px solid #4caf70;
            }  
            .button2:hover {
            background-color: #4caf70;
            color: white;
            }
        </style>
    </head>

    <body>
        {% block navbar %}
            {% include 'partials/_navbar.html' %}
        {% endblock %}
      
        <h3>NoteForm</h3>
        <hr>
        
        <form action="" method="POST">
            {%csrf_token%}
            {{form|crispy}}
            <a href="{% url 'lab_4:indexlab4' %}" class="button button1">Back</a>
            <input type="submit" class="button button2">
        </form>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
    </body>
</html>

lab_4/templates/indexlab4.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
        <meta charset="UTF-8"/>
        <title>Node List</title>
        <style>
            a {
                color: inherit;
                text-decoration: none;
            }
            /* https://www.w3schools.com/css/css_table.asp */
            /* table {
              border-collapse: collapse;
              width: 100%;
            }
            
            th, td {
              text-align: left;
              padding: 8px;
            }
            
            tr:nth-child(even){background-color: #f2f2f2}
            
            th {
              background-color: #04AA6D;
              color: white;
            }
            tr:hover {background-color: rgb(208, 208, 208)}  */
            /* https://www.w3schools.com/css/tryit.asp?filename=trycss_buttons_hover */
            .button {
            background-color: #4CAF50; /* Green */
            border: none;
            color: white;
            padding: 16px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            transition-duration: 0.4s;
            cursor: pointer;
            }
            .button1 {padding: 10px 24px;}
            .button1 {
            background-color: white; 
            color: black; 
            border: 2px solid #4CAF50;
            }  
            .button1:hover {
            background-color: #4CAF50;
            color: white;
            }

            .button2 {padding: 10px 24px;}
            .button2 {
            background-color: white; 
            color: black; 
            border: 2px solid #e5ff00;
            }  
            .button2:hover {
            background-color: #e5ff00;
            color: rgb(5, 5, 5);
            }       

            .button3 {padding: 10px 24px;}
            .button3 {
            background-color: white; 
            color: black; 
            border: 2px solid #ce1212;
            }  
            .button3:hover {
            background-color: #ce1212;
            color: rgb(2, 2, 2);
            }

        </style>
    </head>
    <body>

      {% block navbar %}
        {% include 'partials/_navbar.html' %}
      {% endblock %}

      {% for message in messages %}
      <p class="alert alert-success mt-3">{{message}}</p>
      {% endfor %}

        <h2>Note List</h2>
        <table class="table table-hover table-bordered">
        <tr>
            <th scope="col">Untuk</th>
            <th scope="col">Dari</th>
            <th scope="col">Title</th>
            <th scope="col">Message</th>
            <th scope="col">Action</th>
        </tr>
        <!-- TODO loop from Friend model -->
        {% for note in notes %}
        <tr>
            <td> <a href="{% url 'lab_4:cardnote' note.id %}" >{{ note.untuk }}</a></td>
            <td> <a href="{% url 'lab_4:cardnote' note.id %}">{{ note.dari }}</a></td>
            <td> <a href="{% url 'lab_4:cardnote' note.id %}">{{ note.title }}</a></td>
            <td>{{ note.message }}</td>
            <td>
              <a href="{% url 'lab_4:editform4' note.id %}" class='button button2'>Edit</a>
              <a href="{% url 'lab_4:deleteform4' note.id %}" class='button button3'>Delete</a>
            </td>
        </tr>
        {% endfor %}
        </table>
    <a href="{% url 'lab_4:createform4' %}" class="button button1" >Add Note</a>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
  </body>
</html>

lab_4/templates/notecard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Note Card</title>
</head>
<body>
    <div class="card">
        <div class="card-header">
            <h5>Dear, {{note.untuk}}</h5>
        </div>
        <div class="card-body">
            <blockquote class="blockquote mb-0">
                <h5 class="card-title">{{note.title}}</h5>
                <p>{{note.message}}</p>
                <footer class="blockquote-footer">{{note.dari}}</footer>
            </blockquote>
        </div>
    </div>
    <a href="{% url 'lab_4:indexlab4' %}" class="btn btn-primary">Back</a>
    <a href="{% url 'lab_4:deleteform4' note.id %}" class='btn btn-danger'>Delete</a>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
</body>
</html>

lab_4/templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <h4>Mikael</h4>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'lab_4:indexlab4' %}" aria-current="page">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'lab_4:createform4' %}" aria-current="page">Form</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>